[package]
name = "hashcons-derive"
version = "0.1.0"
authors = ["Nick Hu <me@nickhu.co.uk>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = { version = "1.0", features = [ "full", "extra-traits", "parsing", "printing", "visit-mut" ] }
quote = "1.0"
proc-macro2 = "*"
