[workspace]
members = [
  "homotopy-core",
  "homotopy-web",
  "homotopy-graphics",
]

exclude = [ "hashcons-derive" ]

[profile.release]
# This makes the compiled code faster and smaller, but it makes compiling slower,
# so it's only enabled in release mode.
lto = true

[profile.dev]
lto = "thin"
opt-level = 3
